class LocationData {
  static const Map<String, List<String>> statesByCountry = {
    'India': [
      'Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 
      'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu', 
      'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 
      'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 
      'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 
      'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 
      'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Other'
    ],
    'United States': [
      'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 
      'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 
      'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 
      'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 
      'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 
      'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 
      'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 
      'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Other'
    ],
    'United Kingdom': [
      'England', 'Northern Ireland', 'Scotland', 'Wales', 'Other'
    ],
    'Other': ['Other'],
  };

  static const Map<String, List<String>> citiesByState = {
    // INDIA
    'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati', 'Kurnool', 'Other'],
    'Arunachal Pradesh': ['Itanagar', 'Tawang', 'Naharlagun', 'Other'],
    'Assam': ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Other'],
    'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Other'],
    'Chhattisgarh': ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Other'],
    'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Other'],
    'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Gandhinagar', 'Other'],
    'Haryana': ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Other'],
    'Himachal Pradesh': ['Shimla', 'Manali', 'Dharamshala', 'Solan', 'Other'],
    'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Other'],
    'Karnataka': ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubli', 'Belagavi', 'Other'],
    'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Other'],
    'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Other'],
    'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Other'],
    'Manipur': ['Imphal', 'Churachandpur', 'Other'],
    'Meghalaya': ['Shillong', 'Tura', 'Other'],
    'Mizoram': ['Aizawl', 'Lunglei', 'Other'],
    'Nagaland': ['Kohima', 'Dimapur', 'Other'],
    'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Other'],
    'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Other'],
    'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Other'],
    'Sikkim': ['Gangtok', 'Namchi', 'Other'],
    'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Other'],
    'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Other'],
    'Tripura': ['Agartala', 'Udaipur', 'Other'],
    'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Prayagraj', 'Noida', 'Other'],
    'Uttarakhand': ['Dehradun', 'Haridwar', 'Roorkee', 'Other'],
    'West Bengal': ['Kolkata', 'Asansol', 'Siliguri', 'Durgapur', 'Other'],
    'Andaman and Nicobar Islands': ['Port Blair', 'Other'],
    'Chandigarh': ['Chandigarh', 'Other'],
    'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa', 'Other'],
    'Delhi': ['New Delhi', 'Delhi', 'Other'],
    'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Other'],
    'Ladakh': ['Leh', 'Kargil', 'Other'],
    'Lakshadweep': ['Kavaratti', 'Other'],
    'Puducherry': ['Pondicherry', 'Oulgaret', 'Other'],

    // UNITED STATES
    'Alabama': ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Other'],
    'Alaska': ['Anchorage', 'Fairbanks', 'Juneau', 'Other'],
    'Arizona': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Other'],
    'Arkansas': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Other'],
    'California': ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose', 'Other'],
    'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Other'],
    'Connecticut': ['Bridgeport', 'New Haven', 'Stamford', 'Hartford', 'Other'],
    'Delaware': ['Wilmington', 'Dover', 'Newark', 'Other'],
    'Florida': ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 'Other'],
    'Georgia': ['Atlanta', 'Augusta', 'Savannah', 'Columbus', 'Other'],
    'Hawaii': ['Honolulu', 'Hilo', 'Kailua', 'Other'],
    'Idaho': ['Boise', 'Meridian', 'Nampa', 'Other'],
    'Illinois': ['Chicago', 'Aurora', 'Springfield', 'Naperville', 'Other'],
    'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'Other'],
    'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Other'],
    'Kansas': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Other'],
    'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Other'],
    'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Other'],
    'Maine': ['Portland', 'Lewiston', 'Bangor', 'Other'],
    'Maryland': ['Baltimore', 'Columbia', 'Annapolis', 'Other'],
    'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Other'],
    'Michigan': ['Detroit', 'Grand Rapids', 'Warren', 'Ann Arbor', 'Other'],
    'Minnesota': ['Minneapolis', 'St. Paul', 'Rochester', 'Other'],
    'Mississippi': ['Jackson', 'Gulfport', 'Southaven', 'Other'],
    'Missouri': ['Kansas City', 'St. Louis', 'Springfield', 'Jefferson City', 'Other'],
    'Montana': ['Billings', 'Missoula', 'Great Falls', 'Helena', 'Other'],
    'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Other'],
    'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'Other'],
    'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Other'],
    'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Trenton', 'Other'],
    'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Other'],
    'New York': ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Other'],
    'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Other'],
    'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks', 'Other'],
    'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Other'],
    'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Other'],
    'Oregon': ['Portland', 'Salem', 'Eugene', 'Other'],
    'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg', 'Other'],
    'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Other'],
    'South Carolina': ['Charleston', 'Columbia', 'North Charleston', 'Other'],
    'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Other'],
    'Tennessee': ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Other'],
    'Texas': ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'Other'],
    'Utah': ['Salt Lake City', 'West Valley City', 'Provo', 'Other'],
    'Vermont': ['Burlington', 'South Burlington', 'Montpelier', 'Other'],
    'Virginia': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Other'],
    'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Olympia', 'Other'],
    'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Other'],
    'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Other'],
    'Wyoming': ['Cheyenne', 'Casper', 'Laramie', 'Other'],

    // UNITED KINGDOM
    'England': ['London', 'Birmingham', 'Manchester', 'Liverpool', 'Leeds', 'Bristol', 'Other'],
    'Scotland': ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee', 'Other'],
    'Wales': ['Cardiff', 'Swansea', 'Newport', 'Other'],
    'Northern Ireland': ['Belfast', 'Derry', 'Lisburn', 'Other'],
    
    'Other': ['Other'],
  };
}
