// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCHJHag0nJj2SeSrPZoXefeuyo4J4Ifs',
    appId: '1:352475496558:web:3a34fd9ecc33ba37f8e67f',
    messagingSenderId: '352475496558',
    projectId: 'casting-29490',
    authDomain: 'casting-29490.firebaseapp.com',
    storageBucket: 'casting-29490.firebasestorage.app',
    measurementId: 'G-FM0K6QMFXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOz0py9JIEu_SLOLRCo3p7f8BO87AwjHc',
    appId: '1:352475496558:android:c7860055a97d0123f8e67f',
    messagingSenderId: '352475496558',
    projectId: 'casting-29490',
    storageBucket: 'casting-29490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATfGPtO2hheaAhDLyA7dWJtavL7-ABlU',
    appId: '1:352475496558:ios:a9bde3b3f4aee214f8e67f',
    messagingSenderId: '352475496558',
    projectId: 'casting-29490',
    storageBucket: 'casting-29490.firebasestorage.app',
    androidClientId: '352475496558-f2rllir8dla499vv4d51f42tj3tdi329.apps.googleusercontent.com',
    iosClientId: '352475496558-4i2inrr0lepc3tvnej1r7rir833k7jns.apps.googleusercontent.com',
    iosBundleId: 'com.example.aicc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBATfGPtO2hheaAhDLyA7dWJtavL7-ABlU',
    appId: '1:352475496558:ios:a9bde3b3f4aee214f8e67f',
    messagingSenderId: '352475496558',
    projectId: 'casting-29490',
    storageBucket: 'casting-29490.firebasestorage.app',
    androidClientId: '352475496558-f2rllir8dla499vv4d51f42tj3tdi329.apps.googleusercontent.com',
    iosClientId: '352475496558-4i2inrr0lepc3tvnej1r7rir833k7jns.apps.googleusercontent.com',
    iosBundleId: 'com.example.aicc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRCHJHag0nJj2SeSrPZoXefeuyo4J4Ifs',
    appId: '1:352475496558:web:03ce068c4d6a4b6df8e67f',
    messagingSenderId: '352475496558',
    projectId: 'casting-29490',
    authDomain: 'casting-29490.firebaseapp.com',
    storageBucket: 'casting-29490.firebasestorage.app',
    measurementId: 'G-1D36TJS0J6',
  );
}
